name: webpaint

services:
  postgres_auth_db:
    image: postgres:15-alpine
    container_name: paint_auth_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paint_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # auth service
  auth_service:
    build: ./auth-service
    container_name: paint_auth_service
    env_file:
      - .env
    environment: 
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8081:8081"
    command: >
      sh -c "
        until pg_isready -h postgres_auth_db -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do
          echo 'Esperando a PostgreSQL...';
          sleep 2;
        done;
        echo 'Base de datos lista. Ejecutando migraciones...';
        alembic upgrade head;
        echo 'Migraciones completadas. Iniciando servidor...';
        uvicorn app.main:app --host 0.0.0.0 --port 8081"
    depends_on:
      - postgres_auth_db
    networks:
      - paint_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8081/health')"]
      interval: 5s
      timeout: 3s
      retries: 5

    
  drawing_service:
    build: ./drawing-service
    container_name: paint_drawing_service
    env_file:
      - .env
    environment:
      - AUTH_URL=http://paint_auth_service:8081/
    ports:
      - "8082:8082"
    depends_on:
      - auth_service
    networks:
      - paint_network

  image_service:
    build: ./image-service
    container_name: paint_image_service
    env_file:
      - .env
    environment:
      - AUTH_URL=http://paint_auth_service:8081/
    ports:
      - "8083:8083"
    depends_on:
      - auth_service
    networks:
      - paint_network


volumes:
  postgres_data:

networks:
  paint_network:
    driver: bridge